name: onlytest
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
    paths:
      - '**.go'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.18
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go install

    - name: Test code
      run: go test -race -coverprofile="coverage.txt" -covermode=atomic github.com/michimani/text-detector/... -shuffle=on

    - name: Upload code coverage to Codecov
      uses: codecov/codecov-action@v2